### ISSUE TITLE
Add domain setting of the Google Captcha to the options

### ISSUE THREAD

**Issue by stulzq** [TimothyMeadows/reCAPTCHA.AspNetCore#18]
Thank you for sharing this practical project. My project is using it. I submitted a pull request to you a few days ago and you merged it. Now I found a small problem during the use, I want to discuss it with you.

I am in China.  Google’s domain  `www.google.com` is blocked by the Chinese government’s firewall. For most Chinese, they don’t have the ability to use VPN to penetrate this firewall. So they won’t be able to use the Google Captcha service properly.  But Google additionally provides a domain to use the Google Captcha service.  So I would like to suggest adding the Domain settings to the option.  I have implemented it for use in my project: https://github.com/stulzq/reCAPTCHA.AspNetCore/blob/unicorn/reCAPTCHA.AspNetCore/RecaptchaService.cs#L52 . If you allow, I can submit a pull request.

Additional domain description: https://developers.google.com/recaptcha/docs/faq

![image](https://user-images.githubusercontent.com/13200155/56133664-879b3980-5fbf-11e9-99ab-643e9477f270.png)

**Comment by TimothyMeadows** [comment]
Hi, i understand your problem. I have no issues extending the library to support recaptcha.net. However some things need to be resolved first. I can't default the library to recatpcha.net over google.com. This is strictly because there is a performance concern between recaptcha.net, and google.com. I can't extend the library in the manor you have done. This creates a security risk. If the application using reCAPTCHA.AspNetCore is compromised in some way (hack, bad employee etc..) you could force the library to use any domain you wanted (such as reverse proxy).

When time permits i will add a static boolean to the RecaptchaService that will allow you to force the recaptcha.net domain over the google.com. Hopefully this will be acceptable for you, and others that suffer from similar censorship concerns.

**Comment by stulzq** [comment]
Yes, I have considered the security issues you considered. I agree with your opinion.

**Comment by TimothyMeadows** [comment]
This has now been resolved in [2.2.3](https://www.nuget.org/packages/reCAPTCHA.AspNetCore/2.2.3).
