### ISSUE TITLE
Add an option to force recatcha to succeed for testing reasons 

### ISSUE THREAD

**Issue by prince272** [TimothyMeadows/reCAPTCHA.AspNetCore#38]
Is it possible to add an option to disable reCAPTCHA making it succeed at all times by simply adding an option to the settings. Enable ReCAPTCHA = true.

**Comment by TimothyMeadows** [comment]
You can do this without needed changes to the package. Simply don't load the recaptcha at all when you don't want to use it. I don't see the value in allowing this as it could be abused in production environments.

**Comment by prince272** [comment]
Hello, Please i don't understand "don't load the recaptcha at all when you don't want to use it. ". Did you mean i shouldn't add it to the dependency services.

**Comment by prince272** [comment]
There might be null exception since the RecaptchaService isn't available,

**Comment by TimothyMeadows** [comment]
Comment out the [ValidateRecaptcha] attribute in your code and it won't be validated anymore but will still exist for the sake of testing. Further, if you don't want to set your local domain you are developing from to the google recaptcha site. You can also comment out the @Html helper.

If you want a more standardized method for dealing with this issue rather than depending on comment tags. You can use the ```IF #DEBUG``` directive to control if the Recaptcha code is triggered at all. Read more here: https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/preprocessor-directives/preprocessor-if
