### ISSUE TITLE
Implementation for Blazor (Server-Side)

### ISSUE THREAD

**Issue by svrebelo001** [TimothyMeadows/reCAPTCHA.AspNetCore#54]
Hi Timothy!

It's great what you have accomplished so far with this middleware.

For people who doesn't work with MVC apps do you have any workaround for Blazor apps?

I'm kinda struggling on this part (idk what to do on the razor page).

`@using (Html.BeginForm("SomeMethod", "SomeController")) {
  @(Html.Recaptcha<RecaptchaV2Checkbox>(RecaptchaSettings?.Value))
}`

Thanks in advance!

**Comment by TimothyMeadows** [comment]
Hi, i can't commit to this library supporting Blazor at this time. Further i personally have absolutely no experience dealing with Blazor. That all being said. If you can't use the MVC helper in the razor page you always try calling it directly via the helper class as it's static.

```csharp
var html = RecaptchaHelper.Recaptcha<RecaptchaV2Checkbox>(RecaptchaSettings?.Value);
```

You can then use whatever method Blazor uses for sending client side html to the user by passing it the HtmlString in the html variable.

Further, you can create an instance the RepcaptchaService class and call it's methods directly rather than depending on an attribute. I can't say i recommend, or support this.
